import type { Product } from './types.js';

export const products: Product[] = [
  // Furnaces (5)
  {
    id: 'p001',
    sku: 'FURN-001',
    name: 'Trane S9V2 96% AFUE Two-Stage Gas Furnace',
    description: 'Two-stage, variable-speed gas furnace with 96% AFUE. Communicating control compatible.',
    price: 1849.0,
    stock: 12,
    category: 'Furnaces',
    manufacturer: 'Trane',
    specs: { afue: '96%', btu: '80000', venting: 'Direct vent' },
  },
  {
    id: 'p002',
    sku: 'FURN-002',
    name: 'Lennox EL296V 96% AFUE Modulating Furnace',
    description: 'Modulating gas furnace with variable-speed blower and iComfort Wi-Fi compatibility.',
    price: 2299.0,
    stock: 8,
    category: 'Furnaces',
    manufacturer: 'Lennox',
    specs: { afue: '96%', btu: '100000', venting: 'Direct vent' },
  },
  {
    id: 'p003',
    sku: 'FURN-003',
    name: 'Carrier 59TN6 95% AFUE Two-Stage Furnace',
    description: 'Two-stage gas furnace with ComfortHeat technology. Eco-friendly silicon nitride igniter.',
    price: 1699.0,
    stock: 15,
    category: 'Furnaces',
    manufacturer: 'Carrier',
    specs: { afue: '95%', btu: '60000' },
  },
  {
    id: 'p004',
    sku: 'FURN-004',
    name: 'Goodman GMSS96 96% AFUE Gas Furnace',
    description: 'Single-stage, multi-speed gas furnace with aluminized steel heat exchanger.',
    price: 1249.0,
    stock: 22,
    category: 'Furnaces',
    manufacturer: 'Goodman',
    specs: { afue: '96%', btu: '80000' },
  },
  {
    id: 'p005',
    sku: 'FURN-005',
    name: 'Rheem R96V 96% AFUE Modulating Furnace',
    description: 'Modulating gas furnace with EcoNet enabled control and variable-speed ECM blower.',
    price: 1999.0,
    stock: 6,
    category: 'Furnaces',
    manufacturer: 'Rheem',
    specs: { afue: '96%', btu: '80000' },
  },

  // Filters (5)
  {
    id: 'p006',
    sku: 'FILT-001',
    name: 'Filtrete MPR 1500 MERV 12 Air Filter (16x25x1, 6-pack)',
    description: 'MERV 12 pleated air filter captures 54% of small particles. Lasts up to 90 days.',
    price: 89.99,
    stock: 150,
    category: 'Filters',
    manufacturer: 'Filtrete',
    specs: { merv: '12', size: '16x25x1', mpr: '1500' },
  },
  {
    id: 'p007',
    sku: 'FILT-002',
    name: 'Honeywell FPR 10 MERV 13 Allergen Filter (20x25x4)',
    description: 'MERV 13 allergen filter for whole-house air cleaners. Captures pollen, dust, and smoke.',
    price: 49.99,
    stock: 78,
    category: 'Filters',
    manufacturer: 'Honeywell',
    specs: { merv: '13', size: '20x25x4' },
  },
  {
    id: 'p008',
    sku: 'FILT-003',
    name: 'AprilAire 213 MERV 13 Media Filter (20x25x4)',
    description: 'MERV 13 high-performance media filter. Self-sealing gasket. OEM replacement.',
    price: 39.99,
    stock: 95,
    category: 'Filters',
    manufacturer: 'AprilAire',
    specs: { merv: '13', size: '20x25x4' },
  },
  {
    id: 'p009',
    sku: 'FILT-004',
    name: 'Nordic Pure MERV 10 Pleated AC Furnace Filter (16x20x1, 12-pack)',
    description: 'MERV 10 pleated filter. Electrostatic synthetic media. Bulk pack of 12.',
    price: 64.99,
    stock: 200,
    category: 'Filters',
    manufacturer: 'Nordic Pure',
    specs: { merv: '10', size: '16x20x1', pack: '12' },
  },
  {
    id: 'p010',
    sku: 'FILT-005',
    name: 'Filtrete Healthy Living MPR 2800 MERV 13 Filter (14x14x1, 2-pack)',
    description: 'MERV 13 allergen and bacteria filter. Captures 62% of particles 0.3-1 micron.',
    price: 24.99,
    stock: 120,
    category: 'Filters',
    manufacturer: 'Filtrete',
    specs: { merv: '13', mpr: '2800', size: '14x14x1' },
  },

  // Thermostats (5)
  {
    id: 'p011',
    sku: 'THERM-001',
    name: 'ecobee Smart Thermostat Premium',
    description: 'Smart thermostat with built-in air quality monitor and voice control.',
    price: 249.99,
    stock: 40,
    category: 'Thermostats',
    manufacturer: 'ecobee',
    specs: { connectivity: 'Wi-Fi', sensors: 'Included' },
  },
  {
    id: 'p012',
    sku: 'THERM-002',
    name: 'Nest Learning Thermostat (4th Gen)',
    description: 'AI-powered learning thermostat with humidity sensor and Matter support.',
    price: 279.0,
    stock: 35,
    category: 'Thermostats',
    manufacturer: 'Nest',
    specs: { connectivity: 'Wi-Fi, Matter' },
  },
  {
    id: 'p013',
    sku: 'THERM-003',
    name: 'Honeywell T9 Smart Thermostat',
    description: 'Smart thermostat with smart room sensors. Multi-room temperature balancing.',
    price: 199.99,
    stock: 50,
    category: 'Thermostats',
    manufacturer: 'Honeywell',
    specs: { connectivity: 'Wi-Fi', sensors: 'Multi-room' },
  },
  {
    id: 'p014',
    sku: 'THERM-004',
    name: 'White-Rodgers 1F80-361 Programmable Thermostat',
    description: '5-1-1 day programmable thermostat. Single-stage heat/cool.',
    price: 49.99,
    stock: 80,
    category: 'Thermostats',
    manufacturer: 'White-Rodgers',
    specs: { programmable: '5-1-1' },
  },
  {
    id: 'p015',
    sku: 'THERM-005',
    name: 'Lux WIN100 Programmable Thermostat',
    description: '7-day programmable touchscreen thermostat. Universal compatibility.',
    price: 39.99,
    stock: 65,
    category: 'Thermostats',
    manufacturer: 'Lux',
    specs: { programmable: '7-day' },
  },

  // Motors (5)
  {
    id: 'p016',
    sku: 'MOT-001',
    name: 'Fasco Blower Motor 1/2 HP Variable Speed',
    description: '1/2 HP variable-speed ECM blower motor. Direct replacement for Trane/AMC.',
    price: 379.0,
    stock: 25,
    category: 'Motors',
    manufacturer: 'Fasco',
    specs: { horsepower: '0.5', type: 'ECM' },
  },
  {
    id: 'p017',
    sku: 'MOT-002',
    name: 'A.O. Smith F48H70A02 Blower Motor',
    description: '1/3 HP 4-speed blower motor. 115V. Replaces many Carrier and Lennox models.',
    price: 189.0,
    stock: 32,
    category: 'Motors',
    manufacturer: 'A.O. Smith',
    specs: { horsepower: '0.33', type: 'PSC' },
  },
  {
    id: 'p018',
    sku: 'MOT-003',
    name: 'Mars 10856 Condenser Fan Motor 1/4 HP',
    description: '1/4 HP condenser fan motor. 825 RPM. 208/230V.',
    price: 159.0,
    stock: 28,
    category: 'Motors',
    manufacturer: 'Mars',
    specs: { horsepower: '0.25', voltage: '230' },
  },
  {
    id: 'p019',
    sku: 'MOT-004',
    name: 'Fasco Draft Inducer Motor 3200 RPM',
    description: 'Replacement draft inducer motor for gas furnaces. Fits Carrier, Bryant, Payne.',
    price: 119.0,
    stock: 45,
    category: 'Motors',
    manufacturer: 'Fasco',
    specs: { speed: '3200 RPM' },
  },
  {
    id: 'p020',
    sku: 'MOT-005',
    name: 'Century UCF Blower Motor Assembly',
    description: '1 HP blower motor assembly with module. Belt-drive rated.',
    price: 449.0,
    stock: 14,
    category: 'Motors',
    manufacturer: 'Century',
    specs: { horsepower: '1', drive: 'Belt' },
  },

  // Controls (5)
  {
    id: 'p021',
    sku: 'CTRL-001',
    name: 'Honeywell ST9120U1003 Universal Furnace Control Board',
    description: 'Universal furnace control board. 5-LED diagnostics. Replaces 200+ part numbers.',
    price: 119.0,
    stock: 38,
    category: 'Controls',
    manufacturer: 'Honeywell',
    specs: { type: 'Furnace control' },
  },
  {
    id: 'p022',
    sku: 'CTRL-002',
    name: 'Carrier HK42FZ007 Control Board',
    description: 'OEM furnace control board for Carrier 58 series. 4-LED diagnostic.',
    price: 219.0,
    stock: 18,
    category: 'Controls',
    manufacturer: 'Carrier',
    specs: { type: 'Furnace control' },
  },
  {
    id: 'p023',
    sku: 'CTRL-003',
    name: 'Mars 11024A Contactor 40A 24V',
    description: '40A 2-pole contactor with 24V coil. Standard AC contactor.',
    price: 24.99,
    stock: 200,
    category: 'Controls',
    manufacturer: 'Mars',
    specs: { amperage: '40A', voltage: '24V coil' },
  },
  {
    id: 'p024',
    sku: 'CTRL-004',
    name: 'GE 45+5 MFD Dual Run Capacitor 440V',
    description: '45+5 MFD dual run capacitor. 440V oval. Replaces many OEM part numbers.',
    price: 18.99,
    stock: 175,
    category: 'Controls',
    manufacturer: 'GE',
    specs: { capacitance: '45+5 MFD', voltage: '440V' },
  },
  {
    id: 'p025',
    sku: 'CTRL-005',
    name: 'White-Rodgers 50A55-843 Universal Furnace Control',
    description: 'White-Rodgers universal furnace control module. Replaces hundreds of OEM controls.',
    price: 159.0,
    stock: 22,
    category: 'Controls',
    manufacturer: 'White-Rodgers',
    specs: { type: 'Furnace control' },
  },
];

export const findProductBySku = (sku: string): Product | undefined =>
  products.find((p) => p.sku === sku);

export const findProductsByCategory = (category: string): Product[] =>
  products.filter((p) => p.category === category);
